language: ruby
rvm:
  - 2.0
  - 1.9.3
  - ruby-head
  - rbx-19mode
  - jruby-19mode
  - jruby-head

matrix:
  allow_failures:
    - rvm: rbx-19mode
    - rvm: jruby-19mode
    - rvm: jruby-head

script:
  - "bundle exec rake ci:all"
